#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller: App\Controller\HomeController::accueil

app_article:
    path: /showArticle/{id}
    controller: App\Controller\ArticleShowController::showArticle

app_addArticle:
    path: /addArticle
    controller: App\Controller\ArticleAddController::addArticle

app_save:
    path: /saveArticle
    controller: App\Controller\ArticleSaveController::saveArticle